### ISSUE TITLE
Typo in man page (fwkit.8)

### ISSUE THREAD

**Issue by smonaica** [mattferris/fwkit#22]
(I feel this is too trivial an issue to bother with a full-fledged pull request.)

There is a mistake on line 15 of the man page (fwkit.8). The line begins with a ".", but it clearly should begin with a "\\".

**Comment by smonaica** [comment]
Lintian found a couple more typos in the man page. I have attached a patch that fixes them all.
[fix-manpage-typos.patch.gz](https://github.com/mattferris/fwkit/files/2476595/fix-manpage-typos.patch.gz)

**Comment by mattferris** [comment]
Thanks! I applied the patch as commit e730613
